"""Data model for evaluation test cases using Pydantic validation."""

from pydantic import BaseModel, Field  # Data validation framework


class EvaluationTestCase(BaseModel):
    """Represents a single test case for LLM evaluation.

    Contains the input prompt, actual LLM output, expected output,
    and optional retrieval context for RAG-based evaluations.
    """

    # The input query or prompt sent to the LLM
    input_text: str = Field(
        ...,
        min_length=1,
        description="The input prompt or query sent to the LLM",
    )

    # The actual output generated by the LLM
    actual_output: str = Field(
        ...,
        min_length=1,
        description="The actual response generated by the LLM",
    )

    # The expected or ground-truth output for comparison
    expected_output: str = Field(
        default="",
        description="The expected or reference output for comparison",
    )

    # Retrieval context documents for RAG evaluations
    retrieval_context: list[str] = Field(
        default_factory=list,
        description="List of context documents used for retrieval-based generation",
    )

    # Additional context provided to the LLM alongside the input
    context: list[str] = Field(
        default_factory=list,
        description="Additional context provided alongside the input",
    )

    # Human-readable name for identifying this test case
    name: str = Field(
        default="",
        description="Optional descriptive name for this test case",
    )

    class Config:
        """Pydantic model configuration options."""

        # Allow population of fields by field name
        populate_by_name = True
        # Generate a JSON schema title for documentation
        json_schema_extra = {
            "example": {
                "input_text": "What is the capital of France?",
                "actual_output": "The capital of France is Paris.",
                "expected_output": "Paris",
                "retrieval_context": ["France is a country in Western Europe. Its capital is Paris."],
                "context": [],
                "name": "capital_france_test",
            }
        }
